application: niubi
version: 1
runtime: python
api_version: 1

default_expiration: "4d 5h"

handlers:
- url: /static
  static_dir: static
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /canvas.html
  static_files: static/html/canvas.html
  upload: static/html/canvas.html

- url: /canvas.html
  static_files: static/html/rpc_relay.html
  upload: static/html/rpc_relay.html
  
- url: /.*
  script: main.py

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin